version: "3.9"

services:
  dev-db:
    image: postgres:16-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory