version: "3.9"

services:
  dev-db:
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: inventory

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"